### PR TITLE
Fix laser to ins position

### PR DESCRIPTION
**Pull request by elemoine**

### CODE REVIEW

**Comment by elemoine** [comment]
This is what I get with this:

qgis 2 18 12 - li3ds_013

@ldgeo last chance PR. Again, I'll merge this, and I'll you test this in lopocs/itowns one more time.

Also, I'll write an issue to pg-li3ds to list and describe all the Stereopolis-specific transform stuff we've added recently. We at least need to document all this.

**Comment by elemoine** [comment]
@ldgeo the tables/views have updated on the server, for you to test once again :) Thanks.

**Comment by ldgeo** [comment]
Not much better... Z is still weird : http://i.imgur.com/1LG86Up.png

**Comment by elemoine** [comment]
Depressing... I still think the current transform is correct than before. Thanks for testing.

**Comment by elemoine** [comment]
@ldgeo what is the problem that you see this time?

In the database I think I see consistent values.

For example, if I run this:

```sql
# create materialized view lidar_points_ins as
select pc_get(points.points, 'z') as z
     , pc_get(points.points, 'time') as m
     , id as patch_id
     , row_number()
  over () as point_id
     , points.points::geometry(pointzm, 2154)
  from "LaVillette_1705160610_00_view" l
     , lateral li3ds.transform(pc_transform(l.points, 100), 2, 17, 1, pc_patchavg(l.points, 'time')) tpatch
     , lateral pc_explode(tpatch) points
where pc_patchmin(l.points, 'x') > 0 and id > 50000 limit 500000;
```

This creates 500.000 points whose coordinates are relative to the INS. And I observe what I think are consistent values for z:

```sql
# select min(st_z(points)), max(st_z(points)) from lidar_points_ins;
        min        |       max       
-------------------+-----------------
 -2.18398532060594 | 16.318880296385
(1 row)
```

So, from -2.18 meters to 16.31 meters relative to the INS. That looks ok.

If I transform the same 500.000 points to coordinates relative to the world this time, I also get consistent results:

```sql
# create materialized view lidar_points_world as
select pc_get(points.points, 'z') as z
     , pc_get(points.points, 'time') as m
     , id as patch_id
     , row_number()
  over () as point_id
     , points.points::geometry(pointzm, 2154)
  from "LaVillette_1705160610_00_view" l
     , lateral li3ds.transform(pc_transform(l.points, 100), 2, 17, 2, pc_patchavg(l.points, 'time')) tpatch
     , lateral pc_explode(tpatch) points
where pc_patchmin(l.points, 'x') > 0 and id > 50000 limit 500000;
```

```sql
# select min(st_z(points)), max(st_z(points)) from lidar_points_world;
       min        |       max        
------------------+------------------
 96.2069865356842 | 113.566358059059
(1 row)
```

So from 96.20 meters to 113.56 meters (world referential). That does not look bad either.

And this is what we have on LaVillette_1705160610_00_building_view:

```sql
# select min(pc_patchmin(tpoints, 'z')), max(pc_patchmax(tpoints, 'z')) from "LaVillette_1705160610_00_building_view";
       min        |       max        
------------------+------------------
 71.8573500362032 | 174.236634268126
(1 row)
```

z values range from 71.85 meters to 174 meters.

**Comment by ldgeo** [comment]
same elevation range in lopocs table : 
```
lopocs=# select min(pc_patchmin(points, 'z')), max(pc_patchmax(points, 'z')) from li3ds_fontaine;
     min     |     max      
-------------+--------------
 71.85699217 | 174.23699217
(1 row
```

**Pull request merged**
